# Generated by Django 5.0.7 on 2024-12-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف'),
        ),
    ]
