# Generated by Django 5.2.6 on 2025-12-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_discount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('price', models.IntegerField(verbose_name='هزینه ارسال')),
            ],
        ),
    ]
