# Generated by Django 5.0.7 on 2024-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=400, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('image', models.ImageField(upload_to='images/slider')),
                ('content', models.CharField(verbose_name='متن')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
        ),
    ]
