# Generated by Django 5.0.7 on 2024-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_slider_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='عکس بنر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ادرس url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('posation', models.CharField(choices=[('list_page', 'صفحه لیست محصولات'), ('detail_list', 'صفحه جزئیات محصولات'), ('contact_us', 'صفحه تماس با ما'), ('article_page', 'صفحه مقالات')], max_length=400, verbose_name='جایگاه نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
