# Generated by Django 5.0.7 on 2024-11-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0003_user_about_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
