# Generated by Django 5.0.7 on 2024-11-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0004_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
