# Generated by Django 5.0.7 on 2024-12-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0005_user_adress'),
        ('product_model', '0012_alter_sampleproductimages_options_commentsproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_model.product', verbose_name='علاقه مندی ها'),
        ),
    ]
