# Generated by Django 5.0.7 on 2024-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0006_user_favorite'),
        ('product_model', '0012_alter_sampleproductimages_options_commentsproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='userfavorites', to='product_model.product', verbose_name='علاقه مندی ها'),
        ),
    ]
