# Generated by Django 5.0.7 on 2025-01-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0007_remove_user_favorite_user_favorite'),
        ('product_model', '0012_alter_sampleproductimages_options_commentsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='userfavorites', to='product_model.product', verbose_name='علاقه مندی ها'),
        ),
    ]
