# Generated by Django 5.2.6 on 2025-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0008_alter_user_favorite'),
        ('product_model', '0013_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='About User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_avatar', verbose_name='User Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email Activation Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='userfavorites', to='product_model.product', verbose_name='Favorites'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
    ]
