# Generated by Django 5.0.7 on 2024-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruductbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='', max_length=300, verbose_name='نام برند'),
        ),
    ]
