# Generated by Django 5.0.7 on 2024-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0004_pruductbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruductbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='', max_length=300, verbose_name='عنوان در url'),
        ),
    ]
