# Generated by Django 5.0.7 on 2024-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0005_alter_pruductbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(verbose_name='عنوان محصول'),
        ),
    ]
