# Generated by Django 5.0.7 on 2024-12-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0007_alter_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatogory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_model.productcatogory', verbose_name='والد'),
        ),
    ]
