# Generated by Django 5.0.7 on 2024-12-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0008_productcatogory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatogory',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
