# Generated by Django 5.0.7 on 2024-12-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0010_visitedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product_images')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_model.product', verbose_name='محصول مورد نظر')),
            ],
        ),
    ]
