# Generated by Django 5.0.7 on 2024-12-16 12:34

import django.db.models.deletion
import product_model.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0011_sampleproductimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleproductimages',
            options={'verbose_name': 'عکس نمونه های محصول', 'verbose_name_plural': 'عکس های نمونه های محصولات'},
        ),
        migrations.CreateModel(
            name='CommentsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='دیدگاه')),
                ('date', models.DateField(blank=True, default=product_model.models.generate_date, null=True, verbose_name='تاریخ')),
                ('time', models.TimeField(blank=True, default=product_model.models.generate_time, null=True, verbose_name='زمان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_model.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه برای محصول',
                'verbose_name_plural': 'دیدگاه ها برای محصولات',
            },
        ),
    ]
