# Generated by Django 5.0.7 on 2024-11-12 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='زمان مقاله'),
        ),
    ]
