# Generated by Django 5.0.7 on 2024-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_article_author_article_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='دسته بندی والد'),
        ),
    ]
