# Generated by Django 5.0.7 on 2024-11-12 15:42

import article_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_alter_articlecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateField(default=article_module.models.get_default_date_now, verbose_name='تاریخ مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(default=article_module.models.get_default_time_now, verbose_name='زمان مقاله'),
        ),
    ]
