# Generated by Django 5.0.7 on 2024-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_alter_article_create_date_alter_article_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500, unique=True, verbose_name='عنوان در url'),
        ),
    ]
